export const themes = {
  fire: {
    key: "fire",
    name: "Fire",
    title: "War God",
    creature: "Primordial Fire",
    element: "War · Fire · Ash",
    image: "./assets/fire.jpg",
    accent: "#e0452c",
    accentSoft: "rgba(224, 69, 44, 0.35)",
    background: "#170504",
    surface: "#26100c",
    ink: "#ffe6dc",
    tagline: "Where silence ends and the drums begin.",
    description:
      "A hunter prowls the temple of embers. Every step is a verdict. Every flame remembers a battle already won.",
    fontDisplay: '"Cinzel", "Iowan Old Style", serif',
    titleWeight: 700,
    titleTracking: "-0.01em",
    taglineStyle: "normal",
  },
  earth: {
    key: "earth",
    name: "Earth",
    title: "Earth Goddess",
    creature: "Wolf",
    element: "Root · Moss · Memory",
    image: "./assets/earth.jpg",
    accent: "#6fa85a",
    accentSoft: "rgba(111, 168, 90, 0.35)",
    background: "#060f08",
    surface: "#0e1d11",
    ink: "#e6f2e2",
    tagline: "The oldest things are still watching.",
    description:
      "A lone wolf stands at the mouth of a mossy gate, where stone gave up long ago and the forest took over.",
    fontDisplay: '"Fraunces", "Iowan Old Style", serif',
    titleWeight: 600,
    titleTracking: "0em",
    taglineStyle: "italic",
  },
  sky: {
    key: "sky",
    name: "Sky",
    title: "Sky God",
    creature: "Swan",
    element: "Air · Light · Distance",
    image: "./assets/sky.jpg",
    accent: "#6db4ef",
    accentSoft: "rgba(109, 180, 239, 0.35)",
    background: "#050c17",
    surface: "#0d1b2e",
    ink: "#e8f3ff",
    tagline: "Stillness is a kind of altitude.",
    description:
      "A swan drifts across a lake that forgot where water ends and sky begins. Nothing here is rushed.",
    fontDisplay: '"Jost", "Century Gothic", sans-serif',
    titleWeight: 300,
    titleTracking: "0.04em",
    taglineStyle: "normal",
  },
};

export const themeOrder = ["fire", "earth", "sky"];
